### ISSUE TITLE
Destroy ASG when LC is updated in-place

### ISSUE THREAD

**Issue by mazzy89** [terraform-aws-modules/terraform-aws-autoscaling#34] opened 2018-06-01 15:42 UTC
One nice "trick" is the fact that once you update the LC, you can trigger a creation of a new ASG. This is done by append to the ASG name the reference to the LC. A discussion about this is [here](https://stackoverflow.com/questions/39345609/how-to-recreate-ec2-instances-of-an-autoscaling-group-with-terraform). However with the following module if we decide to create both ASG and LC, this couldn't be achieved. There is any reason behind this choice in the design?

**Comment by antonbabenko** [comment] 2018-06-03 11:55
[v2.6.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v2.6.0) has been released and it contains the lifecycle which will make sure that ASG is also recreated before deleting old one as described in the link you posted.

**Comment by Rowern** [comment] 2018-06-13 17:06
I think what mazzy was trying to tell is that if for instance we use this module for lc and asg creation and we update the lc (for instance the ami), the asg will not get destroyed and re-created.
On way to achieve this would be to use the generated name from the lc.
For now the work around is to use this module two time, one for the lc and one for the asg rendering this module useless for us...

**Comment by luckytaxi** [comment] 2018-06-14 11:50
So, why was this closed? This module doesn't work as intended (unless I'm missing it's use case) because changes to the LC does does not spawn a new ASG. I'm not sure the 'name_prefix` is the correct option to use.

**Comment by Rowern** [comment] 2018-06-15 07:18
Indeed, this issue should be re-open @antonbabenko

**Comment by antonbabenko** [comment] 2018-06-20 10:17
Thank you all for raising this issue here.

v2.6.0 added functionality which is not related to this issue and I closed this issue by accident.

The proper solution to the current issue can be that we introduce another boolean variable named `recreate_asg_when_lc_changes`. If it is set to `true` then [random_pet](https://www.terraform.io/docs/providers/random/r/pet.html) resource will be used to append to ASG name_prefix.

I will make a PR for this now.

**Closed** 2018-06-20 11:32 UTC

**Comment by antonbabenko** [comment] 2018-06-20 11:34
[v2.7.0](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases/v2.7.0) has been released.

Please test it and report if there is something missing. It is a backward-compatible release, so you should add `recreate_asg_when_lc_changes = true` in arguments to the module to get it to work.
